sudo: required
language: python

python:
  - "2.7"

before_install:
  - pip install -r requirements_test.txt   
  - pip install travis-sphinx   

install:  
  - python setup.py install

script: 
  - coverage run ./setup.py test

after_success:
  - codecov
