sudo: required
language: python
python:
  - "2.7"

# command to install dependencies copied this from like many github toolboxes out there
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH  
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda  
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION      
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm  
  
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib theano
  - pip install codecov  
  - pip install --user travis-sphinx    
  - pip install -r requirements.txt   
  - pip install pytest 
  - python setup.py install

# command to run tests
script: 
  - coverage 
  - pytest tests

after_success:
  - codecov -t f909168e-4b27-4ebe-b49a-670b81635128
  - bash <(curl -s https://codecov.io/bash)

