sudo: required
language: python
python:
  - "2.7"

# command to install dependencies copied this from like many github toolboxes out there
before_install:
  - pip install -U pip  
  - pip install -r requirements.txt   
  - pip install -U travis-sphinx    
  - pip install pytest 

# Install packages
install:  
  - python setup.py install
  - pip install python-coveralls  

# command to run tests
script: 
  - python setup.py test

after_success:
  - coveralls

